sonar.projectKey=shopping-cart-localization
sonar.projectName=shopping-cart-localization
sonar.projectVersion=1.0
sonar.sources=src/main/java/com/example/cart/database
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.token=squ_cdbf7025f8ba4a53b71e43e6968a39c1c1750578
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml